apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: happywalrus
spec:
  selector:
    matchLabels:
      app: happywalrus
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: happywalrus
    spec:
      containers:
      - name: happywalrus
        image: gcr.io/happy-walrus/react-app:v1
        ports:
        - containerPort: 80